---
- name: Deploy Node.js App in Docker Container
  hosts: web
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Pull Docker image
      docker_image:
        name: siddhi17/nodejs-app
        source: pull

    - name: Run Docker container
      docker_container:
        name: nodejs-app
        image: siddhi17/nodejs-app 
        ports:
          - "80:3000"
        state: started
        restart_policy: always

